=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/tokenLists.dtd
<!--Further information is available in XmlDeclarations.java if this is not sufficient-->

<!-- A list of tokens -->
<!ELEMENT tokenLists (tokenList)+>
<!ELEMENT tokenList (token)+>
<!ATTLIST tokenList tagname (alkaneStemComponent|alkaneStemModifier|biochemicalLinkage|bridgeFormingO|carbohydrateRingSize|chargeSpecifier|closebracket|cyclo|dlStereochemistry|fractionalMultiplier|functionalClass|functionalGroup|functionalModifier|fusedRingBridge|group|heteroatom|hydro|hyphen|ine|infix|hydrocarbonFusedRingSystem|multiplier|NA|openbracket|oxidationNumberSpecifier|polyCyclicSpiro|ringAssemblyMultiplier|stereoChemistry|structuralCloseBracket|structuralOpenBracket|subtractivePrefix|suffix|suffixPrefix|unsaturator) #REQUIRED
                    type (acidReplacingFunctionalGroup|acidStem|aminoAcid|anhydro|basic|carbohydrate|carbohydrateConfigurationalPrefix|chain|charge|cisOrTrans|chalcogenAcidStem|dehydro|deoxy|diValentGroup|EorZ|endoExoSynAnti|functionalClass|group|inline|monoValentGroup|monoValentStandaloneGroup|nonCarboxylicAcid|ring|simpleGroup|substituent|root|VonBaeyer) #IMPLIED
                    subType (alkaneStem|anhydride|arylGroup|arylSubstituent|biochemical|carbohydrateStemAldose|carbohydrateStemKetose|cycleformer|cyclicUnsaturableHydrocarbon|dedicatedFunctionalReplacementPrefix|elementaryAtom|endInAn|endInIc|endInIne|epoxyLike|groupStem|halideOrPseudoHalide|hantzschWidman|heteroStem|fusionRing|simpleGroup|multiRadicalSubstituent|noAcyl|none|oxidoLike|perhalogeno|phospho|saltComponent|simpleSubstituent|substituent|systematicCarbohydrateStemAldose|systematicCarbohydrateStemKetose|terminal|ylForAcyl|ylForNothing|ylForYl) #IMPLIED
                    symbol CDATA #REQUIRED
                    ignoreWhenWritingXML (yes) #IMPLIED>
<!-- tagname == the name of the XML element that tokens in this file will be translated to
type == the type attribute on the XML element (for example indicates that a group is an aminoAcid)
subType == the subType attribute on the XML element (gives additional information about what exactly the tokens represent)
symbol == the one-letter code for the token, used by the grammar in regexes.xml 
ignoreWhenWritingXML == Tells the parser not to form an XML element out of these tokens. That means that these token are only syntactic and contain no useful information and are not useful after parsing has completed-->

<!ELEMENT token (#PCDATA)>
<!ATTLIST token value CDATA #REQUIRED
        labels CDATA #IMPLIED
        fusedRingNumbering CDATA #IMPLIED
        defaultInLocant CDATA #IMPLIED
        defaultInID CDATA #IMPLIED
        outIDs CDATA #IMPLIED
        acceptsAdditiveBonds CDATA #IMPLIED
        iminoLike CDATA #IMPLIED
        naturalEntIsOpposite CDATA #IMPLIED
        functionalIDs CDATA #IMPLIED
        addGroup CDATA #IMPLIED
        addHeteroAtom CDATA #IMPLIED
        addBond CDATA #IMPLIED
        usableAsAJoiner CDATA #IMPLIED
        frontLocantsExpected CDATA #IMPLIED
        suffixAppliesTo CDATA #IMPLIED
        suffixAppliesToByDefault CDATA #IMPLIED
        additionalValue CDATA #IMPLIED
        commonOxidationStatesAndMax CDATA #IMPLIED
        alphaBetaClockWiseAtomOrdering CDATA #IMPLIED
        locant CDATA #IMPLIED>
<!--
  (the #PCDATA inside the tag) = the string to match
  value == Meaning depends on the name of the element e.g. SMILES for group, value of multipler for multiplier etc.

  labels == What the locants are for this group. See the SMILESFragmentBuilder class
  fusedRingNumbering ==same as above but for some rings with non standard numbering. This numbering is used to decide which sides correspond to the letters employed in fusing rings. It is neccesary where non standard numbering does not precess regularly around the edge of the fused ring system c.f. purine
  defaultInLocant == The locant of the atom which by default an incoming fragment should connect to. Typically used on groups
  defaultInID == As above but using the id of the atom instead. IDs are relative to this particular fragment
  outIDs == Comma separated ids of locations of radicals on a substituent. Typically used on substituents to create multivalent substituents. IDs are relative to this particular fragment
  acceptsAdditiveBonds == yes or abscent. If present indicates that subsituents (single radicals) will form additive bonds to this group when it has no hydrogen
  iminoLike == yes or abscent. If present indicates that the substituent can either be -X- or X= or even -X=. It changes some behaviour to ecnourage substitutive bonding rather than additive bonds where this substituent is involved. This attribute is mostly ignored when doing polymers for which imino is always -N-
  functionalIDs == Comma seperated ids of locations which are functionalIDs on a group. IDs are relative to this particular fragment. Functional IDs are used in ester formation.
  addGroup == list of the following format: SMILESofGroupToBeAdded space ("id"|"locant"|"defaultId"|"defaultLocant") space (id|locant) [space locantLabel]. If multiple groups are to be added seperate by semicolons e.g. "=O defaultLocant 9;=O defaultLocant 10" to add two double bonded oxygens, one by default at locant 9 and the other by default at locant 10. Use "locant" if name is unambiguous even when locants are not provided. MUST be used in conjunction with the frontLocantsExpected attribute
  addHeteroAtom == list of the following format: element of atom space ("id"|"locant"|"defaultId"|"defaultLocant") space (id|locant). If multiple heteroatoms are to be added seperate by semicolons e.g. "N defaultLocant 1;S defaultLocant 3". Use "locant" if name is unambiguous even when locants are not provided. MUST be used in conjunction with the frontLocantsExpected attribute
  addBond == list of the following format: order of bond space ("id"|"locant"|"defaultId"|"defaultLocant") space (id|locant). If multiple bonds are to be added seperate by semicolons e.g. "2 defaultLocant 1;3 defaultLocant 3". Use "locant" if name is unambiguous even when locants are not provided. MUST be used in conjunction with the frontLocantsExpected attribute
  usableAsAJoiner == "no" or missing. If no then make sure not to use it as such when assigning implicit brackets
  frontLocantsExpected == comma seperated list of locants indicating what locants are expected in front of this group. If one of these locants are found it will preferentially be assigned to the suffix of the group. The group should correspond to a retained name. (codified in P-29.6 of IUPAC 2004 rules)
  suffixAppliesTo == comma seperated ids indicating where the suffix following a group should be applied. Currently used to direct the formation of trivial di-acids. IDs are relative to this particular fragment
  suffixAppliesToByDefault == same as suffixAppliesTo but can be overriden by given locants
  additionalValue == Another value that the token takes. Currently only used for suffixes that mean the addition of two discrete suffixes
  commonOxidationStatesAndMax == For elements, the typical oxidation states (comma seperated) then a colon and the maximum oxidation station. e.g. for iron "2,3:6" as 2 and 3 are typical. 6 is possible but atypical.
  alphaBetaClockWiseAtomOrdering == Listed in a clockwiese order, the locants of the atoms that define a pseudo 2D plane for alpha/beta stereochemistry.
  locant == used for an/ane to prevent a locant being given
  -->

=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/naturalProducts.xml
<!DOCTYPE tokenLists SYSTEM "tokenLists.dtd">
<!-- See the DTD for more details -->
<tokenLists>
	<tokenList tagname="group" type="ring" subType="biochemical" symbol="╢">
<!--alkaloids-->
		<token value="C1[C@@H]2C[C@@H]3[C@H]1[C@H](CC2)[C@H]1C[C@@H]2[C@H]4CCC[C@@]32[C@@H]1NC4" labels="14/13/12/10/9/8/15/16/7/6/5/4/3/2/1/11/17/18/19" valType="SMILES" alphaBetaClockWiseAtomOrdering="10/9/8/7/6/5/4/3/2/1/11">aconit</token>
		<token value="c1cccc2[C@@]34CCCC[C@H]3[C@@H](Cc12)NCC4" labels="1/2/3/4/12/13/5/6/7/8/14/9/10/11/17/16/15" valType="SMILES" alphaBetaClockWiseAtomOrdering="1/11/19/9/14/8/7/6/5/13/12/4/3/2">morphin</token>
		<token value="[C@H]12CCC[C@@H]3CC1.N23C" labels="1/2/3/4/5/6/7/8/9" valType="SMILES" alphaBetaClockWiseAtomOrdering="1/2/3/4/5/6/7">trop</token>
<!--steroids-->
		<token value="[CH3][C@@]12[CH2][CH2][CH2][C@H]1[C@@H]1[CH2][CH2][CH]3[CH2][CH2][CH2][CH2][C@]3([CH3])[C@H]1[CH2][CH2]2" labels="18/13/17/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">androst</token>
		<token value="[CH3][CH]([CH3])[C@H]([CH3])[CH2][CH2][C@@H]([CH3])[C@H]1[CH2][CH2][C@H]2[C@@H]3[CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@]4([CH3])[C@H]3[CH2][CH2][C@]12[CH3]" labels="26/25/27/24/28/23/22/20/21/17/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12/13/18" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">campest</token>
		<token value="[CH3][CH2][CH2][C@@H]([CH3])[C@H]1[CH2][CH2][C@H]2[C@@H]3[CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@]4([CH3])[C@H]3[CH2][CH2][C@]12[CH3]" labels="24/23/22/20/21/17/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12/13/18" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">chol</token>
		<token value="[CH3][CH]([CH3])[CH2][CH2][CH2][C@@H]([CH3])[C@H]1[CH2][CH2][C@H]2[C@@H]3[CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@]4([CH3])[C@H]3[CH2][CH2][C@]12[CH3]" labels="26/25/27/24/23/22/20/21/17/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12/13/18" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">cholest</token>
		<token value="[CH3][CH]([CH3])[C@@H]([CH3])[CH2][CH2][C@@H]([CH3])[C@H]1[CH2][CH2][C@H]2[C@@H]3[CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@]4([CH3])[C@H]3[CH2][CH2][C@]12[CH3]" labels="26/25/27/24/28/23/22/20/21/17/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12/13/18" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">ergost</token>
		<token value="[CH3][C@@]12[CH2][CH2][CH2][C@H]1[C@@H]1[CH2][CH2][CH]3[CH2][CH2][CH2][CH2][C@@H]3[C@H]1[CH2][CH2]2" labels="18/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9/11/12" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">estr</token>
		<token value="[CH3][C@@]12[CH2][CH2][CH2][C@H]1[C@@H]1[CH2][CH2][CH]3[CH2][CH2][CH2][CH2][C@@H]3[C@H]1[CH2][CH2]2" labels="18/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9/11/12" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">oestr</token>
		<token value="[CH3][CH]([CH3])[CH2][CH2][CH]1[O][C@H]2[CH2][C@H]3[C@@H]4[CH2][CH2][CH]5[CH2][CH2][CH2][CH2][C@]5([CH3])[C@H]4[CH2][CH2][C@]3([CH3])[C@H]2[C@@H]1[CH3]" labels="27/25/26/24/23/22/UnlabelledO/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12/13/18/17/20/21" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/20/22/UnlabelledO/16/15/14/8/7/6/5/4/3/2/1/10/9">furost</token>
		<token value="[CH2]1[CH2][C@H]2[CH2][CH2][C@H]3[C@@H]([CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@H]34)[C@@H]2[CH2]1" labels="16/17/13/12/11/9/8/7/6/5/4/3/2/1/10/14/15" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">gon</token>
		<token value="[CH3][CH]([CH3])[C@@H]([CH3])[C@@]1([CH3])[CH2][C@@H]1[C@@H]([CH3])[C@H]1[CH2][CH2][C@H]2[C@@H]3[CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@]4([CH3])[C@H]3[CH2][CH2][C@]12[CH3]" labels="26/25/27/24/28/23/33/34/22/20/21/17/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12/13/18" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">gorgoste</token>
		<token value="[CH3][CH2][C@@H]([CH2][CH2][C@@H]([CH3])[C@H]1[CH2][CH2][C@H]2[C@@H]3[CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@]4([CH3])[C@H]3[CH2][CH2][C@]12[CH3])[CH]([CH3])[CH3]" labels="29/28/24/23/22/20/21/17/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12/13/18/25/26/27" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">poriferast</token>
		<token value="[CH3][CH2][C@H]1[CH2][CH2][C@H]2[C@@H]3[CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@]4([CH3])[C@H]3[CH2][CH2][C@]12[CH3]" labels="21/20/17/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12/13/18" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">pregn</token>
		<token value="[CH3][C@H]1[C@H]2[C@H]([CH2][C@H]3[C@@H]4[CH2][CH2][CH]5[CH2][CH2][CH2][CH2][C@]5([CH3])[C@H]4[CH2][CH2][C@]23[CH3])[O][C@]11[CH2][CH2][CH]([CH3])[CH2][O]1" labels="21/20/17/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12/13/18/UnlabelledO/22/23/24/25/27/26/" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/20/22/UnlabelledO/16/15/14/8/7/6/5/4/3/2/1/10/9">spirost</token>
		<token value="[CH3][CH2][C@H]([CH2][CH2][C@@H]([CH3])[C@H]1[CH2][CH2][C@H]2[C@@H]3[CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@]4([CH3])[C@H]3[CH2][CH2][C@]12[CH3])[CH]([CH3])[CH3]" labels="29/28/24/23/22/20/21/17/16/15/14/8/7/6/5/4/3/2/1/10/19/9/11/12/13/18/25/26/27" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">stigmast</token>

<!--misc-->
		<token value="CCCCCCC[C@H]1CCC[C@@H]1CCCCCCCC" labels="1/2/3/4/5/6/7/8/9/10/11/12/13/14/15/16/17/18/19/20" valType="SMILES" alphaBetaClockWiseAtomOrdering="8/12/11/10/9">prost</token>
		<token value="CCCCCCC[C@H]1CCCO[C@@H]1CCCCCCCC" labels="1/2/3/4/5/6/7/8/9/10/11/11a/12/13/14/15/16/17/18/19/20" valType="SMILES" alphaBetaClockWiseAtomOrdering="8/12/11a/11/10/9">thrombox</token>
	</tokenList>
	<tokenList tagname="group" type="ring" subType="biochemical" symbol="G">
<!--steroids-->
		<token value="[CH3][C@]12[CH2][CH2][C@H]3[C@@H]([CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@]34[CH3])[C@H]1[CH2][CH2][C@@H]2[C@H]1[CH2][CH2][C](=[O])[O][CH2]1" labels="18/13/12/11/9/8/7/6/5/4/3/2/1/10/19/14/15/16/17/20/22/23/24///21" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">bufanolide</token>
		<token value="[CH3][C@]12[CH2][CH2][C@H]3[C@@H]([CH2][CH2][CH]4[CH2][CH2][CH2][CH2][C@]34[CH3])[C@H]1[CH2][CH2][C@@H]2[C@@H]1[CH2][O][C](=[O])[CH2]1" labels="18/13/12/11/9/8/7/6/5/4/3/2/1/10/19/14/15/16/17/20/21//23//22" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">cardanolide</token>

	<!--not retained-->
	<token value="[CH3][CH]([CH3])[CH2][CH2][CH2][C@@H]([CH3])[C@H]1[CH2][CH2][C@H]2[C@@H]3[CH2][CH]=C4[CH2][C@@H](O)[CH2][CH2][C@]4([CH3])[C@H]3[CH2][CH2][C@]12[CH3]" labels="26/25/27/24/23/22/20/21/17/16/15/14/8/7/6/5/4/3//2/1/10/19/9/11/12/13/18" valType="SMILES" alphaBetaClockWiseAtomOrdering="11/12/13/17/16/15/14/8/7/6/5/4/3/2/1/10/9">cholesterol</token>
	</tokenList>

	<tokenList tagname="group" type="ring" subType="biochemical" symbol="z">
<!--alkaloids-->
		<token value="c1ccc2CCN(C)C3Cc4ccccc4c1c23" labels="1/2/3/3a/4/5/6/12/6a/7/7a/8/9/10/11/11a/11b/11c" valType="SMILES" alphaBetaClockWiseAtomOrdering="1/2/3/3a/4/5/6/6a/7/7a/8/9/10/11/11a/11b">aporphin</token>
		<token value="c1cccc2CCN3Cc4ccccc4CC3c12" labels="1/2/3/4/4a/5/6/7/8/8a/9/10/11/12/12a/13/13a/13b" valType="SMILES" alphaBetaClockWiseAtomOrdering="1/2/3/4/4a/5/6/7/8/8a/9/10/11/12/12a/13/13a/13b">berbin</token>
		<token value="C1CN[C@@H]2Cc3c[nH]c4cccc([C@H]2C1)c34" labels="8/7/6/5/4/3/2/1/15/14/13/12/11/10/9/16" valType="SMILES" alphaBetaClockWiseAtomOrdering="1/15/14/13/12/11/10/9/8/7/6/5/4/3/2">ergolin</token>
<!--misc-->
		<token value="S1CCCN2[C@H]1CC2=O" labels="1/2/3/4/5/6/7/8/" valType="SMILES" alphaBetaClockWiseAtomOrdering="1/2/3/4/5/8/7/6">cepham</token>
		<token value="S1CCN2[C@H]1CC2=O" labels="1/2/3/4/5/6/7/" valType="SMILES" alphaBetaClockWiseAtomOrdering="1/2/3/4/7/6/5">penam</token>
	</tokenList>
</tokenLists>

=== dan2097/opsin/core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/miscTokens.xml
<!DOCTYPE tokenLists SYSTEM "tokenLists.dtd">
<!-- See the DTD for more details -->
<tokenLists>
  <tokenList tagname="hydrocarbonFusedRingSystem" symbol="V"><!--the a is part of the multiplier and the e is assumed to be optional -->
    <token value="polyacene">cen</token>
    <token value="polyalene">len</token>
    <token value="polyaphene">phen</token><!--ambiguity between this and multiplier phenyl e.g. hexaphenylbenzene is resolved in the ComponentGenerator generally in favour of phenyl-->
    <token value="polyphenylene">phenylen</token>
    <token value="polynaphthylene">naphthylen</token>
    <token value="polyhelicene">helicen</token>
  </tokenList>
  
  <tokenList tagname="cyclo" symbol="C">
    <token value="cyclo">cyclo</token>
    <token value="cyclo">cyclo-</token>
  </tokenList>

  <tokenList tagname="hydro" symbol="y">
    <token value="dehydro">dehydro</token>
    <token value="hydro">hydro</token>
  </tokenList>
  <tokenList tagname="hydro" symbol="ú">
    <token value="perhydro">perhydro</token>
  </tokenList>

  <tokenList tagname="stereoChemistry" type="cisOrTrans" symbol="t">
    <token value="cis">cis</token>
    <token value="trans">trans</token>
  </tokenList>

  <tokenList tagname="ine" symbol="î"><!--used for amino acids-->
    <token value="ine">ine</token>
    <token value="ine">in</token>
  </tokenList>

  <tokenList tagname="group" type="substituent" subType="multiRadicalSubstituent" symbol="ó"><!--chalcogen replacement terms-->
    <token value="S" labels="none" outIDs="1,1" valType="SMILES" usableAsAJoiner="yes" acceptsAdditiveBonds="yes">thio</token>
    <token value="[SeH2]" labels="none" outIDs="1,1" valType="SMILES" usableAsAJoiner="yes" acceptsAdditiveBonds="yes">seleno</token>
    <token value="[TeH2]" labels="none" outIDs="1,1" valType="SMILES" usableAsAJoiner="yes" acceptsAdditiveBonds="yes">telluro</token>
  </tokenList>

  <tokenList tagname="suffix" type="root" symbol="Ñ">
    <token value="amine">ylamine</token>
  </tokenList>

  <tokenList tagname="polyCyclicSpiro" symbol="º">
    <token value="spirobi">spirobi</token>
    <token value="spirobi">spirobi-</token>
    <token value="spiroter">spiroter</token>
    <token value="spiroter">spiroter-</token>
  </tokenList>

  <tokenList tagname="polyCyclicSpiro" symbol="⌐">
    <token value="spiro">spiro</token>
    <token value="spiro">spiro-</token>
  </tokenList>

  <tokenList tagname="polyCyclicSpiro" symbol="╝">
    <token value="spiroOldMethod">spiro</token>
    <token value="spiroOldMethod">spiro-</token>
  </tokenList>

  <tokenList tagname="dlStereochemistry" symbol="╛">
    <token value="d">d-</token>
    <token value="l">l-</token>
    <token value="dl">dl-</token>
<!--used to distinguish amino acid D/L from carbohydrate D/L if desired-->
    <token value="ds">ds-</token>
    <token value="dg">dg-</token>
    <token value="ls">ls-</token>
    <token value="lg">lg-</token>
  </tokenList>

<!--As a purely non-detachable prefixe-->
	<tokenList tagname="subtractivePrefix" symbol="┐">
		<token value="O">deoxy</token>
		<token value="O">desoxy</token><!--older variant spelling-->
	</tokenList>

<!--As a detachable prefix (which could itself have non-detachable prefixes in the case where it is being treated as a non-detachable prefix)-->
	<tokenList tagname="subtractivePrefix" symbol="x">
		<token value="O">deoxy</token>
		<token value="O">desoxy</token><!--older variant spelling-->
	</tokenList>
</tokenLists>

=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/hwHeteroAtoms.xml
<!DOCTYPE tokenLists SYSTEM "tokenLists.dtd">
<!-- See the DTD for more details -->
<tokenLists>
  <!--For convenience in order of priority-->
  <tokenList tagname="heteroatom" symbol="D"><!--complete set including 2004 recommendations -->
    <token value="F" valType="SMILES">fluora</token>
    <token value="Cl" valType="SMILES">chlora</token>
    <token value="Br" valType="SMILES">broma</token>
    <token value="I" valType="SMILES">ioda</token>
    <token value="O" valType="SMILES">oxa</token>
    <token value="S" valType="SMILES">thia</token>
    <token value="[Se]" valType="SMILES">selena</token>
    <token value="[Te]" valType="SMILES">tellura</token>
    <token value="N" valType="SMILES">aza</token>
    <token value="P" valType="SMILES">phospha</token>
    <token value="[As]" valType="SMILES">arsa</token>
    <token value="[Sb]" valType="SMILES">stiba</token>
    <token value="[Bi]" valType="SMILES">bisma</token>
    <token value="[Si]" valType="SMILES">sila</token>
    <token value="[Ge]" valType="SMILES">germa</token>
    <token value="[Sn]" valType="SMILES">stanna</token>
    <token value="[Pb]" valType="SMILES">plumba</token>
    <token value="B" valType="SMILES">bora</token>
    <token value="[Al]" valType="SMILES">aluma</token>
    <token value="[Ga]" valType="SMILES">galla</token>
    <token value="[In]" valType="SMILES">indiga</token>
    <token value="[Tl]" valType="SMILES">thalla</token>
    <token value="[Hg]" valType="SMILES">mercura</token>

    <token value="F" valType="SMILES">fluor</token>
    <token value="Cl" valType="SMILES">chlor</token>
    <token value="Br" valType="SMILES">brom</token>
    <token value="I" valType="SMILES">iod</token>
    <token value="O" valType="SMILES">ox</token>
    <token value="S" valType="SMILES">thi</token>
    <token value="[Se]" valType="SMILES">selen</token>
    <token value="[Te]" valType="SMILES">tellur</token>
    <token value="N" valType="SMILES">az</token>
    <token value="P" valType="SMILES">phosph</token>
    <token value="[As]" valType="SMILES">ars</token>
    <token value="[Sb]" valType="SMILES">stib</token>
    <token value="[Bi]" valType="SMILES">bism</token>
    <token value="[Si]" valType="SMILES">sil</token>
    <token value="[Ge]" valType="SMILES">germ</token>
    <token value="[Sn]" valType="SMILES">stann</token>
    <token value="[Pb]" valType="SMILES">plumb</token>
    <token value="B" valType="SMILES">bor</token>
    <token value="[Al]" valType="SMILES">alum</token>
    <token value="[Ga]" valType="SMILES">gall</token>
    <token value="[In]" valType="SMILES">indig</token>
    <token value="[Tl]" valType="SMILES">thall</token>
    <token value="[Hg]" valType="SMILES">mercur</token>

    <token value="P" valType="SMILES">phosphor</token>
    <token value="[As]" valType="SMILES">arsen</token>
    <token value="[Sb]" valType="SMILES">antimon</token>
  </tokenList>

  <tokenList tagname="heteroatom" symbol="J"><!--hetero atoms that are compatable with an ine HWsuffix-->
    <token value="O" valType="SMILES">oxa</token>
    <token value="S" valType="SMILES">thia</token>
    <token value="[Se]" valType="SMILES">selena</token>
    <token value="[Te]" valType="SMILES">tellura</token>
    <token value="N" valType="SMILES">aza</token>
    <token value="[Bi]" valType="SMILES">bisma</token>
    <token value="[Si]" valType="SMILES">sila</token>
    <token value="[Ge]" valType="SMILES">germa</token>
    <token value="[Sn]" valType="SMILES">stanna</token>
    <token value="[Pb]" valType="SMILES">plumba</token>
    <token value="[Hg]" valType="SMILES">mercura</token>

    <token value="O" valType="SMILES">ox</token>
    <token value="S" valType="SMILES">thi</token>
    <token value="[Se]" valType="SMILES">selen</token>
    <token value="[Te]" valType="SMILES">tellur</token>
    <token value="N" valType="SMILES">az</token>
    <token value="[Bi]" valType="SMILES">bism</token>
    <token value="[Si]" valType="SMILES">sil</token>
    <token value="[Ge]" valType="SMILES">germ</token>
    <token value="[Sn]" valType="SMILES">stann</token>
    <token value="[Pb]" valType="SMILES">plumb</token>
    <token value="[Hg]" valType="SMILES">mercur</token>

    <token value="P" valType="SMILES">phosphor</token>
    <token value="[As]" valType="SMILES">arsen</token>
    <token value="[Sb]" valType="SMILES">antimon</token>
  </tokenList>

  <tokenList tagname="heteroatom" symbol="j"><!--hetero atoms that are compatable with an ane HWsuffix-->
    <token value="O" valType="SMILES">oxa</token>
    <token value="S" valType="SMILES">thia</token>
    <token value="[Se]" valType="SMILES">selena</token>
    <token value="[Te]" valType="SMILES">tellura</token>
    <token value="[Bi]" valType="SMILES">bisma</token>
    <token value="[Hg]" valType="SMILES">mercura</token>

    <token value="O" valType="SMILES">ox</token>
    <token value="S" valType="SMILES">thi</token>
    <token value="[Se]" valType="SMILES">selen</token>
    <token value="[Te]" valType="SMILES">tellur</token>
    <token value="[Bi]" valType="SMILES">bism</token>
    <token value="[Hg]" valType="SMILES">mercur</token>

    <token value="[As]" valType="SMILES">arsen</token>
  </tokenList>
</tokenLists>
