=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/tokenList.dtd
<!-- See tokenLists.dtd for further explanation of these terms -->
<!ELEMENT tokenList (token)+>
<!ATTLIST tokenList tagname (alkaneStemComponent|alkaneStemModifier|bridgeFormingO|carbohydrateRingSize|chargeSpecifier|closebracket|cyclo|dlStereochemistry|functionalClass|functionalGroup|functionalModifier|group|heteroatom|hydro|hyphen|ine|infix|hydrocarbonFusedRingSystem|multiplier|NA|openbracket|oxidationNumberSpecifier|polyCyclicSpiro|ringAssemblyMultiplier|stereoChemistry|structuralCloseBracket|structuralOpenBracket|subtractivePrefix|suffix|suffixPrefix|unsaturator) #REQUIRED
                    type (acidStem|aminoAcid|basic|carbohydrateConfigurationalPrefix|chain|charge|cisOrTrans|chalcogenAcidStem|diValentGroup|functionalClass|group|inline|monoValentGroup|monoValentStandaloneGroup|nonCarboxylicAcid|ring|simpleGroup|substituent|root|VonBaeyer) #IMPLIED
                    subType (alkaneStem|anhydride|arylGroup|arylSubstituent|biochemical|carbohydrate|cyclicUnsaturableHydrocarbon|dedicatedFunctionalReplacementPrefix|elementaryAtom|endInAn|endInIc|endInIne|epoxyLike|functionalClassGroup|groupStem|halideOrPseudoHalide|hantzschWidman|heteroStem|fusionRing|simpleGroup|multiRadicalSubstituent|noAcyl|none|oxidoLike|perhalogeno|simpleSubstituent|substituent|terminal|ylForAcyl|ylForNothing|ylForYl) #IMPLIED
                    symbol CDATA #REQUIRED
                    ignoreWhenWritingXML (yes) #IMPLIED>

<!ELEMENT token (#PCDATA)>
<!ATTLIST token value CDATA #REQUIRED
        valType (SMILES|dbkey) #IMPLIED
        labels CDATA #IMPLIED
        fusedRingNumbering CDATA #IMPLIED
        defaultInLocant CDATA #IMPLIED
        defaultInID CDATA #IMPLIED
        outIDs CDATA #IMPLIED
        acceptsAdditiveBonds CDATA #IMPLIED
        iminoLike CDATA #IMPLIED
        functionalIDs CDATA #IMPLIED
        addGroup CDATA #IMPLIED
        addHeteroAtom CDATA #IMPLIED
        addBond CDATA #IMPLIED
        usableAsAJoiner CDATA #IMPLIED
        frontLocantsExpected CDATA #IMPLIED
        suffixAppliesTo CDATA #IMPLIED
        suffixAppliesToByDefault CDATA #IMPLIED
        additionalValue CDATA #IMPLIED
        commonOxidationStatesAndMax CDATA #IMPLIED
        alphaBetaClockWiseAtomOrdering CDATA #IMPLIED
        locant CDATA #IMPLIED>

=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/suffixPrefix.xml
<!DOCTYPE tokenList SYSTEM "tokenList.dtd">
<!--
A limiting list of prefixes that modify the meaning of the following prefixes
Not all suffixes appear to accept a suffixPrefix
value is the SMILES for this suffixPrefix
-->
<tokenList tagname="suffixPrefix" symbol="Â¬">
	<token value="C">carb</token>
	<token value="C">carbo</token>
	<token value="C">carbox</token>
	<token value="C">carbono</token>

	<token value="S=O">sulfon</token>
	<token value="S=O">sulfono</token>
	<token value="S">sulfin</token>
	<token value="S">sulfino</token>

	<token value="[SeH?]=O">selenon</token>
	<token value="[SeH?]=O">selenono</token>
	<token value="[SeH?]">selenin</token>
	<token value="[SeH?]">selenino</token>

	<token value="[TeH?]=O">telluron</token>
	<token value="[TeH?]=O">tellurono</token>
	<token value="[TeH?]">tellurin</token>
	<token value="[TeH?]">tellurino</token>


	<!--not recommended by IUPAC-->
	<token value="PO">phosphon</token>
	<token value="PO">phosphono</token>
	<token value="[AsH?]O">arson</token>
	<token value="[AsH?]O">arsono</token>
	<token value="[SbH?]O">stibon</token>
	<token value="[SbH?]O">stibono</token>
</tokenList>

=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/substituents.xml
<!DOCTYPE tokenList SYSTEM "tokenList.dtd">
<!-- See the DTD for more details -->
<tokenList tagname="group" type="substituent" subType="substituent" symbol="X">
  <token value="B" labels="none" usableAsAJoiner="yes">bor</token>
  <token value="[SiH4]" labels="none" usableAsAJoiner="yes">sil</token>
  <token value="[GeH4]" labels="none" usableAsAJoiner="yes">germ</token>
  <token value="[SnH4]" labels="none" usableAsAJoiner="yes">stann</token>
  <token value="[PbH4]" labels="none" usableAsAJoiner="yes">plumb</token>

  <token value="CCc1cc2OCOc2cc1" labels="none">homopiperon</token>
  <token value="C/C=C(C)/CCC[C@H](C)CCC[C@H](C)CCCC(C)C" labels="none">phyt</token>
  <token value="CC(=O)c1ccccc1" labels="///1/2,ortho/3,meta/4,para/5/6">phenac</token>
  <token value="Cc1cc2OCOc2cc1" labels="none">piperon</token>
  <token value="Cc1c(O)cccc1" labels="/1/2,ortho//3,meta/4,para/5/6" defaultInID="4">salic</token>
  <token value="CC=C" usableAsAJoiner="yes">all</token>
  <token value="CC=C" usableAsAJoiner="yes">allan</token>
  <token value="C=C" usableAsAJoiner="yes">vin</token>
</tokenList>

=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/infixes.xml
<!DOCTYPE tokenList SYSTEM "tokenList.dtd">
<!-- value is:
A comma seperated list of:
SMILES bond type to oxygen
O (for oxygen)
(optional and currently ignored) SMILES bond type from oxygen

then the SMILES replacement
-->
<tokenList tagname="infix" symbol="Â¢">
	<token value="-O:N">amid</token>
	<token value="-O:N=[N+]=[N-]">azid</token>
	<token value="-O:Br">bromid</token>
	<token value="-O:Cl">chlorid</token>
	<token value="-O:OC#N">cyanatid</token>
	<token value="-O:C#N">cyanid</token>
	<token value="-O-:SS">dithioperox</token>
	<token value="-O-:[Se|2][Se|2]">diselenoperox</token>
	<token value="-O-:[Te|2][Te|2]">ditelluroperox</token>
	<token value="-O:F">fluorid</token>
	<token value="-O:NN">hydrazid</token>
	<token value="=O:=NN">hydrazon</token>
	<token value="=O:=N">imid</token>
	<token value="-O:I">iodid</token>
	<token value="-O:N=C=O">isocyanatid</token>
	<token value="-O:[N|4+]#[C-]">isocyanid</token>
	<token value="-O:N=C=S">isothiocyanatid</token>
	<token value="-O:N=C=[Se]">isoselenocyanatid</token>
	<token value="-O:N=C=[Te]">isotellurocyanatid</token>
	<token value="#O:#N">nitrid</token>
	<token value="-O-:OO">perox</token>
	<token value="=O,-O:[SeH?]">selen</token>
	<token value="=O,-O:[TeH?]">tellur</token>
	<token value="=O,-O:S">thi</token>
	<token value="-O:SC#N">thiocyanatid</token>
	<token value="-O:[Se|2]C#N">selenocyanatid</token>
	<token value="-O:[Te|2]C#N">tellurocyanatid</token>

	<!--<token value="-O-:SO">thioperoxo</token> is it SO or OS???-->
	<!--<token value="-O-:[Se|2]S">selenothioperoxo</token> is it [Se|2]S or S[Se|2]???-->

	<token value="=O:=NO">hydroxim</token><!--not an IUPAC infix-->
</tokenList>

=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/inlineChargeSuffixes.xml
<!DOCTYPE tokenList SYSTEM "tokenList.dtd">
<!-- See the DTD for more details -->
<!-- value = a reference to suffixRules.xml -->   
<tokenList tagname="suffix" type="charge" symbol="I">
  <token value="ium">ium</token>
  <token value="ide">ide</token>
  <token value="ide">id</token>
  <token value="ylium">ylium</token>
  <token value="ylium">(ylium)</token>
  <token value="uide">uide</token>
  <token value="uide">uid</token>
</tokenList>
