=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/wordRules.dtd
<!ELEMENT wordRules (wordRule+)>

<!ELEMENT wordRule (word)+>
<!ATTLIST wordRule name   CDATA #REQUIRED
                   type   (full|substituent|functionalTerm|polymer) #REQUIRED

>

<!ELEMENT word EMPTY>
<!ATTLIST word type (full|substituent|functionalTerm) #REQUIRED
               value CDATA #IMPLIED
               endsWithRegex CDATA #IMPLIED
               functionalGroupType CDATA #IMPLIED
               endsWithGroupValueAtr CDATA #IMPLIED
               endsWithGroupType CDATA #IMPLIED
               endsWithGroupSubType CDATA #IMPLIED
>

=== dan2097/opsin/core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/wordRules.xml
<!DOCTYPE wordRules SYSTEM "wordRules.dtd">
<!--These are set of rules indicating what words may be combined and what the rule for combining them is
These rules are hard coded into the structure builder.
Rules are checked in the order they are listed in this file so the order is potentially important. Hence also less used word rules appear lower for speed
The result of this process is that the relevant words are placed with a wordRule element which can be thought of as a word of the type defined
in the WordRule's type attribute.

If none of these wordRules match a substituent may merge with an adjacent substituent to form a larger substituent
and a substituent may merge with a full to form a larger full
Parsing will fail if the end result is not one or more full terms or a polymer.
-->
<!--need to be added: hydrazide, lactone, lactam, lactims, sultams and sultims-->
<wordRules>
  <wordRule name="monovalentFunctionalGroup" type="full">
    <word type="substituent" />
    <word type="functionalTerm" functionalGroupType="monoValentGroup"/>
  </wordRule>

  <wordRule name="monovalentFunctionalGroup" type="full">
    <word type="substituent" />
    <word type="functionalTerm" functionalGroupType="monoValentStandaloneGroup"/>
    <word type="functionalTerm" functionalGroupType="monoValentStandaloneGroup"/>
    <word type="functionalTerm" functionalGroupType="monoValentStandaloneGroup"/>
  </wordRule>

  <wordRule name="monovalentFunctionalGroup" type="full">
    <word type="substituent" />
    <word type="functionalTerm" functionalGroupType="monoValentStandaloneGroup"/>
    <word type="functionalTerm" functionalGroupType="monoValentStandaloneGroup"/>
  </wordRule>

  <wordRule name="monovalentFunctionalGroup" type="full">
    <word type="substituent" />
    <word type="functionalTerm" functionalGroupType="monoValentStandaloneGroup"/>
  </wordRule>

  <wordRule name="ester" type="full">
    <word type="substituent" />
    <word type="full" endsWithRegex="(ate|amide|ite)[\]\)\}]*"/>
  </wordRule>

  <wordRule name="amide" type="full">
    <word type="full" endsWithRegex="(ic|ous)([ ]?(acid)?)?[\]\)\}]*"/>
    <word type="full" endsWithRegex="amide[\]\)\}]*" endsWithGroupValueAtr="[N-]"/>
  </wordRule>

  <wordRule name="functionalClassEster" type="full">
    <word type="full" endsWithRegex="(ic|ous)([ ]?(acid)?)?[\]\)\}]*"/>
    <word type="substituent" />
    <word type="functionalTerm" value="ester" />
  </wordRule>

  <wordRule name="functionalClassEster" type="full">
    <word type="full" endsWithRegex="(ate|amide|ite)[\]\)\}]*"/>
    <word type="substituent" />
    <word type="functionalTerm" value="ester" />
  </wordRule>

  <wordRule name="multiEster" type="full">
    <word type="substituent" />
    <word type="substituent" />
    <word type="full" endsWithRegex="(ate|amide|ite)[\]\)\}]*"/>
  </wordRule>
  <wordRule name="multiEster" type="full"><!-- e.g. methyl ethyl propyl phosphate-->
    <word type="substituent" />
    <word type="substituent" />
    <word type="substituent" />
    <word type="full" endsWithRegex="(ate|amide|ite)[\]\)\}]*"/>
  </wordRule>

  <wordRule name="divalentFunctionalGroup" type="full">
    <word type="substituent" />
    <word type="substituent" />
    <word type="functionalTerm" />
  </wordRule>

  <wordRule name="divalentFunctionalGroup" type="full">
    <word type="substituent"/>
    <word type="functionalTerm" functionalGroupType="diValentGroup" />
  </wordRule>

  <wordRule name="glycol" type="full">
    <word type="substituent" endsWithRegex="(diyl|ylene)[\]\)\}]*" />
    <word type="functionalTerm" value="glycol" />
  </wordRule>

  <wordRule name="oxide" type="full">
    <word type="full" endsWithRegex="(?&lt;!ic|ous)" />
    <word type="functionalTerm" endsWithRegex="oxide" functionalGroupType="functionalClass" />
  </wordRule>

  <wordRule name="carbonylDerivative" type="full">
    <word type="full" />
    <word type="substituent" />
    <word type="functionalTerm" endsWithRegex="^(oxime|hydrazone|semicarbazone|thiosemicarbazone|selenosemicarbazone|tellurosemicarbazone|imide)[\]\)\}]*" />
  </wordRule>

  <wordRule name="carbonylDerivative" type="full">
    <word type="full" />
    <word type="functionalTerm" endsWithRegex="(oxime|hydrazone|semicarbazone|imide)[\]\)\}]*" />
  </wordRule>

  <wordRule name="anhydride" type="full">
    <word type="full" endsWithRegex="(ic|ous)([ ]?(acid)?)?[\]\)\}]*"/>
    <word type="full" endsWithRegex="(ic|ous)([ ]?(acid)?)?[\]\)\}]*"/>
    <word type="functionalTerm" endsWithRegex="anhydride[\]\)\}]*"/>
  </wordRule>

  <wordRule name="anhydride" type="full">
    <word type="full" endsWithRegex="(ic|ous)([ ]?(acid)?)?[\]\)\}]*"/>
    <word type="functionalTerm" endsWithRegex="anhydride[\]\)\}]*"/>
  </wordRule>

  <wordRule name="functionGroupAsGroup" type="full">
    <word type="functionalTerm" functionalGroupType="monoValentStandaloneGroup"/>
  </wordRule>

  <wordRule name="acetal" type="full">
    <word type="full" />
    <word type="substituent" />
    <word type="substituent" />
    <word type="functionalTerm" endsWithRegex="(acetal|ketal)" />
  </wordRule>

  <wordRule name="acetal" type="full">
    <word type="full" />
    <word type="substituent" />
    <word type="functionalTerm" endsWithRegex="(acetal|ketal)" />
  </wordRule>

  <wordRule name="acetal" type="full">
    <word type="full" />
    <word type="functionalTerm" endsWithRegex="(acetal|ketal)" />
  </wordRule>

  <wordRule name="polymer" type="polymer">
    <word type="functionalTerm" value="poly"/>
    <word type="substituent"/>
  </wordRule>

  <wordRule name="polymer" type="polymer">
    <word type="functionalTerm" value="oligo"/>
    <word type="substituent"/>
  </wordRule>
</wordRules>
