=== dan2097/opsin/core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/suffixApplicability.dtd
<!ELEMENT suffixApplicability (groupType)+>

<!ELEMENT groupType     (suffix)+>
<!ATTLIST groupType type CDATA #REQUIRED>

<!ELEMENT suffix (#PCDATA)>
<!ATTLIST suffix value CDATA #REQUIRED
               subType CDATA #IMPLIED>

=== dan2097/opsin/core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/suffixApplicability.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE suffixApplicability SYSTEM "suffixApplicability.dtd">
<!-- This file dictates what suffixes are applicabily to the group types that OPSIN recognises.
There are currently 3 main types: acidStem, substituent, standardGroup.
Other types are used under specific conditions e.g. chalcogenAcidStem, aminoAcid, mononuclearNonCarbonOxoAcid
If a type in OPSIN corresponds to a group type then it is used:
Hence acidStem is OPSIN type acidStem
All other groups are classified as standardGroup
In some cases it is further specified that a suffix only applies to a certain subtype e.g. yl has different meanings to different acids

The value of the suffix elements corresponds to the value attribute of the suffixes in suffixes.xml/inlineSuffixes.xml whilst the text is what should be looked up in suffixRules
-->
<suffixApplicability>
  <groupType type="substituent"><!--e.g. bor to boryl -->
    <suffix value="carbonyl">carbonyl</suffix>
    <suffix value="ide">ide</suffix>
    <suffix value="ium">ium</suffix>
    <suffix value="oxy">oxy</suffix>
    <suffix value="oyl">oyl</suffix>
    <suffix value="selenenyl">selenenyl</suffix>
    <suffix value="seleninyl">seleninyl</suffix>
    <suffix value="selenonyl">selenonyl</suffix>
    <suffix value="sulfenyl">sulfenyl</suffix>
    <suffix value="sulfinyl">sulfinyl</suffix>
    <suffix value="sulfonyl">sulfonyl</suffix>
    <suffix value="tellurenyl">tellurenyl</suffix>
    <suffix value="tellurinyl">tellurinyl</suffix>
    <suffix value="telluronyl">telluronyl</suffix>
    <suffix value="uide">uide</suffix>
    <suffix value="yl">yl</suffix>
    <suffix value="ylidene">ylidene</suffix>
    <suffix value="ylidyne">ylidyne</suffix>
    <suffix value="ylium">ylium</suffix>
  </groupType>

  <groupType type="acidStem"><!--e.g. acet to acetamide -->
    <suffix value="aldehyde">aldehyde</suffix>
    <suffix value="amide">amide</suffix>
    <suffix value="amidine">amidine</suffix>
    <suffix value="amidium">amidium</suffix>
    <suffix value="amido">amido</suffix>
    <suffix value="anilide">anilide</suffix>
    <suffix value="ate">ate</suffix>
    <suffix value="hydrazide">hydrazide</suffix>
    <suffix value="hydroxamate">hydroxamate</suffix>
    <suffix value="hydroxamic">hydroxamic</suffix>
    <suffix value="hydroximate">hydroximate</suffix>
    <suffix value="hydroximic">hydroximic</suffix>
    <suffix value="hydroximoyl">hydroximoyl</suffix>
    <suffix value="ic">ic</suffix>
    <suffix value="ide">ide</suffix>
    <suffix value="ium">ium</suffix>
    <suffix value="ite">ite</suffix>
    <suffix value="nitrile">nitrile</suffix>
    <suffix value="nitrilium">nitrilium</suffix>
    <suffix value="onaphthone">onaphthone</suffix>
    <!-- one is handled by hard coding common examples of its use -->
    <suffix value="ophenone">ophenone</suffix>
    <suffix value="ous">ous</suffix>
    <suffix value="oxy" subType="ylForAcyl">oxy-ylForAcyl</suffix>
    <suffix value="oxy" subType="oylForAcyl">oxy</suffix>
    <suffix value="oyl">oyl</suffix>
    <suffix value="uide">uide</suffix>
    <suffix value="yl" subType="ylForAcyl">oyl</suffix>
    <suffix value="yl" subType="oylForAcyl">yl</suffix>
    <suffix value="ylidene" subType="oylForAcyl">ylidene</suffix>
    <suffix value="ylidyne" subType="oylForAcyl">ylidyne</suffix>
    <suffix value="ylidene" subType="ylForAcyl">oxoAndDiYl</suffix>
    <suffix value="ylidyne" subType="ylForAcyl">oxoAndTriYl</suffix>
    <suffix value="ylium">ylium</suffix>
  </groupType>

  <groupType type="aminoAcid"><!--e.g. glycine -> glycinol -->
    <suffix value="al">aldehyde</suffix>
    <suffix value="aldehyde">aldehyde</suffix>
    <suffix value="amide">amide</suffix>
    <suffix value="amidium">amidium</suffix>
    <suffix value="amido">amido</suffix>
    <suffix value="anilide">anilide</suffix>
    <suffix value="ate">ate</suffix>
    <suffix value="ic">ic</suffix>
    <suffix value="ium">ium</suffix>
    <suffix value="ol">ol</suffix>
    <suffix value="oyl">oyl</suffix>
    <suffix value="yl">oyl</suffix>
    <suffix value="aminoAcidYl">yl</suffix><!--locanted yl means something different to unlocanted yl!-->
  </groupType>

  <groupType type="chalcogenAcidStem"><!--e.g. sulfon to sulfonyl -->
    <suffix value="amide">amine</suffix>
    <suffix value="amido">amino</suffix>
    <suffix value="ate">ite</suffix>
    <suffix value="ic">ous</suffix>
    <suffix value="oyl">diyl</suffix>
    <suffix value="yl">diyl</suffix>
    <suffix value="ylidene">ylidene</suffix>
  </groupType>

  <groupType type="nonCarboxylicAcid"><!--e.g. phosphor to phosphoric/phosphourous/phosphoryl-->
    <suffix value="ate">ate_nonCarboxylic</suffix>
    <suffix value="ic">ic_nonCarboxylic</suffix>
    <suffix value="ite">ite_nonCarboxylic</suffix>
    <suffix value="ous">ous_nonCarboxylic</suffix>
    <suffix value="yl" subType="ylForAcyl">oyl_nonCarboxylic</suffix>
    <suffix value="oyl">oyl_nonCarboxylic</suffix>
  </groupType>

  <groupType type="standardGroup"><!--e.g. ethan to ethanimine-->
    <suffix value="al">aldehyde</suffix>
    <suffix value="aldehyde">aldehyde</suffix>
    <suffix value="amide">amide</suffix>
    <suffix value="amidine">amidine</suffix>
    <suffix value="amidium">amidium</suffix>
    <suffix value="amido">amido</suffix>
    <suffix value="amine">amine</suffix>
    <suffix value="aminide">aminide</suffix>
    <suffix value="aminium">aminium</suffix>
    <suffix value="anilide">anilide</suffix>
    <suffix value="ate">ate</suffix>
    <suffix value="carbonyl">carbonyl</suffix>
    <suffix value="carboxylic">carboxylic</suffix>
    <suffix value="carboxylate">carboxylate</suffix>
    <suffix value="carboxylite">carboxylite</suffix>
    <suffix value="diazonium">diazonium</suffix>
    <suffix value="hydrazide">hydrazide</suffix>
    <suffix value="hydrazonic">hydrazonic</suffix>
    <suffix value="hydroxamate">hydroxamate</suffix>
    <suffix value="hydroxamic">hydroxamic</suffix>
    <suffix value="hydroximate">hydroximate</suffix>
    <suffix value="hydroximic">hydroximic</suffix>
    <suffix value="hydroximoyl">hydroximoyl</suffix>
    <suffix value="ic">ic</suffix>
    <suffix value="ide">ide</suffix>
    <suffix value="imine">imine</suffix>
    <suffix value="iminide">iminide</suffix>
    <suffix value="iminium">iminium</suffix>
    <suffix value="io">io</suffix>
    <suffix value="ium">ium</suffix>
    <suffix value="ite">ite</suffix>
    <suffix value="nitrile">nitrile</suffix>
    <suffix value="nitrilium">nitrilium</suffix>
    <suffix value="ol">ol</suffix>
    <suffix value="olate">olate</suffix>
    <suffix value="onaphthone">onaphthone</suffix>
    <suffix value="one">one</suffix>
    <suffix value="ophenone">ophenone</suffix>
    <suffix value="ous">ous</suffix>
    <suffix value="oxy">oxy</suffix>
    <suffix value="oyl">oyl</suffix>
    <suffix value="selenenic">selenenic</suffix>
    <suffix value="selenenyl">selenenyl</suffix>
    <suffix value="seleninyl">seleninyl</suffix>
    <suffix value="selenonyl">selenonyl</suffix>
    <suffix value="selone">selone</suffix>
    <suffix value="sulfenamide">sulfenamide</suffix>
    <suffix value="sulfenamido">sulfenamido</suffix>
    <suffix value="sulfenic">sulfenic</suffix>
    <suffix value="sulfenoselenoic">sulfenoselenoic</suffix>
    <suffix value="sulfenoselenoyl">sulfenoselenoyl</suffix>
    <suffix value="sulfenothioic">sulfenothioic</suffix>
    <suffix value="sulfenothioyl">sulfenothioyl</suffix>
    <suffix value="sulfenyl">sulfenyl</suffix>
    <suffix value="sulfinyl">sulfinyl</suffix>
    <suffix value="sulfonyl">sulfonyl</suffix>
    <suffix value="tellone">tellone</suffix>
    <suffix value="tellurenic">tellurenic</suffix>
    <suffix value="tellurenyl">tellurenyl</suffix>
    <suffix value="tellurinyl">tellurinyl</suffix>
    <suffix value="telluronyl">telluronyl</suffix>
    <suffix value="thiolate">thiolate</suffix>
    <suffix value="uide">uide</suffix>
    <suffix value="yl">yl</suffix>
    <suffix value="ylidene">ylidene</suffix>
    <suffix value="ylidyne">ylidyne</suffix>
    <suffix value="ylium">ylium</suffix>

<!-- INCOMPLETE-->
    <suffix value="boronic">boronic</suffix>
  </groupType>
</suffixApplicability>

=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/suffixApplicability.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE suffixApplicability SYSTEM "suffixApplicability.dtd">
<!-- This file dictates what suffixes are applicabily to the group types that OPSIN recognises.
There are currently 3 main types: acidStem, substituent, standardGroup.
Other types are used under specific conditions e.g. chalcogenAcidStem, aminoAcid, mononuclearNonCarbonOxoAcid
If a type in OPSIN corresponds to a group type then it is used:
Hence acidStem is OPSIN type acidStem
All other groups are classified as standardGroup
In some cases it is further specified that a suffix only applies to a certain subtype e.g. yl has different meanings to different acids

The value of the suffix elements corresponds to the value attribute of the suffixes in suffixes.xml/inlineSuffixes.xml whilst the text is what should be looked up in suffixRules
-->
<suffixApplicability>
  <groupType type="substituent"><!--e.g. bor to boryl -->
    <suffix value="carbonyl">carbonyl</suffix>
    <suffix value="ide">ide</suffix>
    <suffix value="ium">ium</suffix>
    <suffix value="oxy">oxy</suffix>
    <suffix value="oyl">oyl</suffix>
    <suffix value="selenenyl">selenenyl</suffix>
    <suffix value="seleninyl">seleninyl</suffix>
    <suffix value="selenonyl">selenonyl</suffix>
    <suffix value="sulfenyl">sulfenyl</suffix>
    <suffix value="sulfinyl">sulfinyl</suffix>
    <suffix value="sulfonyl">sulfonyl</suffix>
    <suffix value="tellurenyl">tellurenyl</suffix>
    <suffix value="tellurinyl">tellurinyl</suffix>
    <suffix value="telluronyl">telluronyl</suffix>
    <suffix value="uide">uide</suffix>
    <suffix value="yl">yl</suffix>
    <suffix value="ylidene">ylidene</suffix>
    <suffix value="ylidyne">ylidyne</suffix>
    <suffix value="ylium">ylium</suffix>
  </groupType>

  <groupType type="acidStem"><!--e.g. acet to acetamide -->
    <suffix value="acylium">acylium</suffix>
    <suffix value="aldehyde">aldehyde</suffix>
    <suffix value="aldoxime">aldoxime</suffix>
    <suffix value="amide">amide</suffix>
    <suffix value="amidylium">amidylium</suffix>
    <suffix value="amidine">amidine</suffix>
    <suffix value="amidinium">amidinium</suffix>
    <suffix value="amidium">amidium</suffix>
    <suffix value="amido">amido</suffix>
    <suffix value="anilide">anilide</suffix>
    <suffix value="ate">ate</suffix>
    <suffix value="hydrazide">hydrazide</suffix>
    <suffix value="hydroxamate">hydroxamate</suffix>
    <suffix value="hydroxamic">hydroxamic</suffix>
    <suffix value="ic">ic</suffix>
    <suffix value="ide">ide</suffix>
    <suffix value="imide">cyclicimide</suffix>
    <suffix value="imidium">cyclicimidium</suffix>
    <suffix value="imido">cyclicimido</suffix>
    <suffix value="imidylium">cyclicimidylium</suffix>
    <suffix value="ium">ium</suffix>
    <suffix value="ite">ite</suffix>
    <suffix value="nitrile">nitrile</suffix>
    <suffix value="nitrilium">nitrilium</suffix>
    <suffix value="onaphthone">onaphthone</suffix>
    <!-- one is handled by hard coding common examples of its use -->
    <suffix value="ophenone">ophenone</suffix>
    <suffix value="ous">ous</suffix>
    <suffix value="oxy" subType="ylForAcyl">oxy-ylForAcyl</suffix>
    <suffix value="oxy" subType="ylForYl">oxy</suffix>
    <suffix value="oyl">oyl</suffix>
    <suffix value="uide">uide</suffix>
    <suffix value="yl" subType="ylForAcyl">oyl</suffix>
    <suffix value="yl" subType="ylForYl">yl</suffix>
    <suffix value="ylidene" subType="ylForYl">ylidene</suffix>
    <suffix value="ylidyne" subType="ylForYl">ylidyne</suffix>
    <suffix value="ylidene" subType="ylForAcyl">oxoAndDiYl</suffix>
    <suffix value="ylidyne" subType="ylForAcyl">oxoAndTriYl</suffix>
    <suffix value="ylium">ylium</suffix>
  </groupType>

  <groupType type="aminoAcid"><!--e.g. glycine -> glycinol -->
    <suffix value="al" subType="endInIne">aldehyde</suffix>
    <suffix value="al" subType="endInAn">aldehyde</suffix>
    <suffix value="aldehyde">aldehyde</suffix>
    <suffix value="aldoxime">aldoxime</suffix>
    <suffix value="amide">amide</suffix>
    <suffix value="amidylium">amidylium</suffix>
    <suffix value="amidium">amidium</suffix>
    <suffix value="amido">amido</suffix>
    <suffix value="anilide">anilide</suffix>
    <suffix value="ate">ate</suffix>
    <suffix value="ic">ic</suffix>
    <suffix value="ium">ium</suffix>
    <suffix value="ol" subType="endInIne">ol</suffix>
    <suffix value="ol" subType="endInAn">ol</suffix>
    <suffix value="oyl">oyl</suffix>
    <suffix value="yl">oyl</suffix>
    <suffix value="oMeaningYl">yl</suffix><!--e.g. glycino-->
    <suffix value="aminoAcidYl">yl</suffix><!--locanted yl means something different to unlocanted yl!-->
  </groupType>

  <groupType type="chalcogenAcidStem"><!--e.g. sulfon to sulfonyl -->
    <suffix value="acylium">ylium</suffix>
    <suffix value="amide">amine</suffix>
    <suffix value="amidylium">aminylium</suffix>
    <suffix value="amido">amino</suffix>
    <suffix value="ate">ite</suffix>
    <suffix value="ic">ous</suffix>
    <suffix value="oyl">diyl</suffix>
    <suffix value="yl">diyl</suffix>
    <suffix value="ylidene">ylidene</suffix>
  </groupType>

  <groupType type="nonCarboxylicAcid"><!--e.g. phosphor to phosphoric/phosphourous/phosphoryl-->
    <suffix value="acylium">acylium_nonCarboxylic</suffix>
    <suffix value="ate">ate_nonCarboxylic</suffix>
    <suffix value="ic">ic_nonCarboxylic</suffix>
    <suffix value="ite">ite_nonCarboxylic</suffix>
    <suffix value="ous">ous_nonCarboxylic</suffix>
    <suffix value="yl" subType="ylForAcyl">oyl_nonCarboxylic</suffix>
    <suffix value="oyl">oyl_nonCarboxylic</suffix>
  </groupType>

  <groupType type="standardGroup"><!--e.g. ethan to ethanimine-->
    <suffix value="acylium">acylium</suffix>
    <suffix value="al">aldehyde</suffix>
    <suffix value="aldehyde">aldehyde</suffix>
    <suffix value="aldoxime">aldoxime</suffix>
    <suffix value="amide">amide</suffix>
    <suffix value="amidylium">amidylium</suffix>
    <suffix value="amidine">amidine</suffix>
    <suffix value="amidinium">amidinium</suffix>
    <suffix value="amidium">amidium</suffix>
    <suffix value="amido">amido</suffix>
    <suffix value="amine">amine</suffix>
    <suffix value="aminide">aminide</suffix>
    <suffix value="aminium">aminium</suffix>
    <suffix value="aminyl">amino</suffix>
    <suffix value="aminylium">aminylium</suffix>
    <suffix value="anilide">anilide</suffix>
    <suffix value="arsonous">arsonous</suffix>
    <suffix value="ate">ate</suffix>
    <suffix value="azonic">azonic</suffix>
    <suffix value="azonate">azonate</suffix>
    <suffix value="azonous">azonous</suffix>
    <suffix value="boronate">boronate</suffix>
    <suffix value="boronic">boronic</suffix>
    <suffix value="carbamic">carbamic</suffix>
    <suffix value="carbonyl">carbonyl</suffix>
    <suffix value="carbonylium">carbonylium</suffix>
    <suffix value="carboxylic">carboxylic</suffix>
    <suffix value="carboxylate">carboxylate</suffix>
    <suffix value="carboxylite">carboxylite</suffix>
    <suffix value="diazonium">diazonium</suffix>
    <suffix value="hydrazide">hydrazide</suffix>
    <suffix value="hydrazonic">hydrazonic</suffix>
    <suffix value="hydroxamate">hydroxamate</suffix>
    <suffix value="hydroxamic">hydroxamic</suffix>
    <suffix value="ic">ic</suffix>
    <suffix value="ide">ide</suffix>
    <suffix value="imine">imine</suffix>
    <suffix value="iminide">iminide</suffix>
    <suffix value="iminium">iminium</suffix>
    <suffix value="iminyl">iminyl</suffix>
    <suffix value="iminylium">iminylium</suffix>
    <suffix value="io">io</suffix>
    <suffix value="ium">ium</suffix>
    <suffix value="ite">ite</suffix>
    <suffix value="nitrile">nitrile</suffix>
    <suffix value="nitrilium">nitrilium</suffix>
    <suffix value="ol">ol</suffix>
    <suffix value="olate">olate</suffix>
    <suffix value="oMeaningYl">yl</suffix><!--e.g. tetrazano-->
    <suffix value="onaphthone">onaphthone</suffix>
    <suffix value="one">one</suffix>
    <suffix value="ophenone">ophenone</suffix>
    <suffix value="ous">ous</suffix>
    <suffix value="oxy">oxy</suffix>
    <suffix value="oyl">oyl</suffix>
    <suffix value="phosphonous">phosphonous</suffix>
    <suffix value="selenenic">selenenic</suffix>
    <suffix value="selenenyl">selenenyl</suffix>
    <suffix value="seleninyl">seleninyl</suffix>
    <suffix value="selenonyl">selenonyl</suffix>
    <suffix value="selone">selone</suffix>
    <suffix value="stibonous">stibonous</suffix>
    <suffix value="sulfamic">sulfamic</suffix>
    <suffix value="sulfenamide">sulfenamide</suffix>
    <suffix value="sulfenamido">sulfenamido</suffix>
    <suffix value="sulfenic">sulfenic</suffix>
    <suffix value="sulfenoselenoic">sulfenoselenoic</suffix>
    <suffix value="sulfenoselenoyl">sulfenoselenoyl</suffix>
    <suffix value="sulfenothioic">sulfenothioic</suffix>
    <suffix value="sulfenothioyl">sulfenothioyl</suffix>
    <suffix value="sulfenyl">sulfenyl</suffix>
    <suffix value="sulfinyl">sulfinyl</suffix>
    <suffix value="sulfonyl">sulfonyl</suffix>
    <suffix value="tellone">tellone</suffix>
    <suffix value="tellurenic">tellurenic</suffix>
    <suffix value="tellurenyl">tellurenyl</suffix>
    <suffix value="tellurinyl">tellurinyl</suffix>
    <suffix value="telluronyl">telluronyl</suffix>
    <suffix value="thione">thione</suffix>
    <suffix value="uide">uide</suffix>
    <suffix value="yl">yl</suffix>
    <suffix value="ylidene">ylidene</suffix>
    <suffix value="ylidyne">ylidyne</suffix>
    <suffix value="ylium">ylium</suffix>
  </groupType>
</suffixApplicability>
